Tracker:AddLocations("locations/A Bad Encounter.json")
Tracker:AddLocations("locations/Apocalink Now.json")
Tracker:AddLocations("locations/Big Bounce Theory.json")
Tracker:AddLocations("locations/Good Luck Splasher.json")
Tracker:AddLocations("locations/Ink In Park.json")
Tracker:AddLocations("locations/Inkorp Express.json")
Tracker:AddLocations("locations/Jump On The Water.json")
Tracker:AddLocations("locations/Let It Bounce.json")
Tracker:AddLocations("locations/Potatoes Ink.json")
Tracker:AddLocations("locations/Ray Man Legend.json")
Tracker:AddLocations("locations/Ray Man Origin.json")
Tracker:AddLocations("locations/Stick On The Water.json")
Tracker:AddLocations("locations/Stick To The Plan.json")
Tracker:AddLocations("locations/Storm Wind.json")
Tracker:AddLocations("locations/The Glados Principle.json")
Tracker:AddLocations("locations/There Will Be Fries.json")
Tracker:AddLocations("locations/Toxink Avenger.json")
Tracker:AddLocations("locations/Toxink Bubbles.json")
Tracker:AddLocations("locations/Troopers Please.json")
Tracker:AddLocations("locations/Water Is Coming.json")
Tracker:AddLocations("locations/Welcome to Inkorp.json")
Tracker:AddLocations("locations/Wind Walker.json")
Tracker:AddLocations("locations/Overworld.json")
